blog_wnb/urls.py
from django.contrib import admin
from django.urls import path, include
 
from . import views

# import things to turn possible get media
from django.conf.urls.static import static
from django.conf import settings

# urls for app
urlpatterns = [
    path('admin/', admin.site.urls), # for admin
    path("", views.home), # route for home 
    path("users/", include("users.urls")), # route for users app
    path("posts/", include("posts.urls")) # route for users app
]

# url for app get media
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

# import views to show views to user
from . import views

# declaring a app name to redirect to this app
app_name = "posts"

urlpatterns = [
    path("createpost/", views.create_post, name="newpost") # path to create new post
]

users/urls.py
from django.urls import path

# import vies to load them on urls
from . import views

# create a app name for redirection
app_name = "users"

urlpatterns = [
    path ("", views.user_home), # path that redirect to register (if the user is logged, will be redirected to home page)
    path ("register/", views.register_view, name="register"), # path to register a user (if the user is logged, will be redirected to home page)
    path ("login/", views.login_view, name="login"), # path to login a user (if the user is logged, will be redirected to home page)
    path("logout/", views.logout_view, name="logout"), # path to logout a user (always redirect to home page)
    path("myprofile/", views.my_profile_view, name="my_profile"),# path to user private profile
    path("<slug:slug>/", views.profile_view, name="profile") # path to user public profile
]

posts/models.py
from django.db import models

# create model for posts
class posts (models.Model) :
    made_by = models.CharField (default="", max_length=50)
    image = models.ImageField (upload_to="posts_pics/")
    title = models.CharField (max_length=100)
    description = models.TextField (default="")
    content_id = models.TextField(default="")
    slug = models.SlugField(default="")

    # define "name" for model
    def __str__ (self) :
        return f"{self.title} <{self.made_by}> "

posts/forms.py
from django import forms

# import ModelForm to form
from django.forms import ModelForm

#import posts to create post Form for it
from .models import posts

# a form to post
class post_form (ModelForm) :
    class Meta :
        # base of the form
        model = posts

        # fields of form
        fields = ["title", "image", "description"]

blog_wnb/posts/views.py
from django.shortcuts import render, redirect

# import login required to make a login required pages
from django.contrib.auth.decorators import login_required

# import post_form to get info from user to create a new form 
from .forms import post_form

# import slugfy to slugfy
from django.utils.text import slugify

# import uuid to create a new unique id
import uuid

# import user_profile from user models to get info about logged user
from users.models import user_profile


@login_required(login_url="users:login") # if user is not logged send him to users:login
def create_post (request) :
    # Get username (email) from user
    user_email = request.user.username

    # getting user from user_profile models by email
    user = user_profile.objects.filter( email = user_email )[0]

    # verify if  request method is post
    if request.method == "POST" : # if it is
        # get form data and files
        form = post_form(request.POST, request.FILES)

        # if its ok with form
        if form.is_valid () :
            # create a unique id with uuid
            new_id = uuid.uuid4()

            # get form data
            form_data= form.cleaned_data

            # create a slug for the form 
            slug = slugify (f"{form_data['title']} <{new_id}> <{user_email}>")

            # set values that dont come with the form but its necessary for the model
            form.instance.slug = slug
            form.instance.made_by = user_email
            form.instance.content_id = new_id

            # save form data
            form.save()

            # redirect to home
            return redirect ("/")
 
    else : # if method is not post
        form = post_form()

    # return create post page
    return render (request, "posts/create_post.html", {
        "form" : form, 
        "user" : user, 
        "is_logged" : True,
        })

posts/views.py
from django.shortcuts import render, redirect

# import login required to make a login required pages
from django.contrib.auth.decorators import login_required

# import post_form to get info from user to create a new form 
from .forms import post_form

# import slugfy to slugfy
from django.utils.text import slugify

# import uuid to create a new unique id
import uuid

# import user_profile from user models to get info about logged user
from users.models import user_profile

from django.contrib.auth import logout

# function to logout superuser
def loggout_superuser (is_super_user) :
    # if user is super user 
    if is_super_user:
        # logout and send to home page
        logout(request)
        return redirect("/")

@login_required(login_url="users:login") # if user is not logged send him to users:login
def create_post (request) :
    # logout super user
    loggout_superuser(request.user.is_superuser)

    # Get username (email) from user
    user_email = request.user.username

    # getting user from user_profile models by email
    user = user_profile.objects.filter( email = user_email )[0]

    # verify if  request method is post
    if request.method == "POST" : # if it is
        # get form data and files
        form = post_form(request.POST, request.FILES)

        # if its ok with form
        if form.is_valid () :
            # create a unique id with uuid
            new_id = uuid.uuid4()

            # get form data
            form_data= form.cleaned_data

            # create a slug for the form 
            slug = slugify (f"{form_data['title']} <{new_id}> <{user_email}>")

            # set values that dont come with the form but its necessary for the model
            form.instance.slug = slug
            form.instance.made_by = user_email
            form.instance.content_id = new_id

            # save form data
            form.save()

            # redirect to home
            return redirect ("/")
 
    else : # if method is not post
        form = post_form()

    # return create post page
    return render (request, "posts/create_post.html", {
        "form" : form, 
        "user" : user, 
        "is_logged" : True,
        })

templates/index.html
{% extends 'template.html' %}

{% block content%}
    {% include 'posts.html' %}
{% endblock %}

templates/posts.html
<div class="posts">
    {% for post_and_user in posts_and_users %}
    <div class="posts_post">
        <div class="posts_post_creator">
            <img src="{{post_and_user.creator.profile_pic.url}}" alt="{{post_and_user.creator.username}}">
            <a href="{% url 'users:profile' slug=post_and_user.creator.slug %}">
                <p>
                    {{post_and_user.creator.username}}
                </p>
            </a>
        </div>
        <div class="posts_post_imageContent">
            <img src="{{post_and_user.post.image.url}}" alt="{{post_and_user.post.title}}" style="width: 300px;">
        </div>
        <div class="posts_post_textContent">
            <h3>
                <strong>{{post_and_user.creator.username}}</strong> {{ post_and_user.post.title }}
            </h3>
            <p>
                {{ post_and_user.post.description }}

            </p>
        </div>
    </div>        

    {% endfor %}
</div>

templates/template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>WNB Blog</title>
</head>
<body>

    <header>
        <div class="header_title">
            <a href="/" class="header_title_a">
                <h1 class="header_title_a--h1">
                    BNW 
                </h1>
            </a>
        </div>

        <div class="header_actions">

        </div>

        <div class="header_user">
        {% if is_logged %}
            <div class="header_user_logged">
                <div class="header_user_logged_info">
                    <p>
                        {{ user.username }}
                    </p>
                    <img src="{{ user.profile_pic.url }}" alt="user image">
                    <div class="header_user_logged_info_options">
                        <a href="{% url 'posts:newpost' %}">
                            <button>
                                new post
                            </button>
                        </a>
                        <a href="{% url 'users:my_profile' %}">
                            <button>
                                account
                            </button>
                        </a>
                        <a href="{% url 'users:logout' %}">
                            <button>
                                logout
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="header_user_notLogged">

                <a href="{% url 'users:register' %}">
                    <button>
                        register
                    </button>
                </a>

                <a href="{% url 'users:login' %}">
                    <button>
                        login
                    </button>
                </a>
            </div>
        {% endif %}
        </div>
    </header>

    {% block content %}
    {% endblock %}
</body>
</html>